"""Video to image sequence. Fast tier -- no Maya, real ffmpeg, real files.

These run a genuine conversion, because ffmpeg ships with the package and the
whole module is a subprocess plus path arithmetic. That is worth having: the
argument list is the kind of thing that looks right and produces a sequence at
the wrong rate, and only running it catches that.

The source videos are generated by ffmpeg itself (`testsrc`), so the suite
needs no fixture files and no third-party dependency beyond the binary already
in `animkit/vendor`.
"""

import os
import subprocess

import pytest

from animkit.core import transcode

requires_ffmpeg = pytest.mark.skipif(
    not transcode.is_available(),
    reason="no ffmpeg -- expected at animkit/vendor/ffmpeg/<platform>/",
)


def make_video(path, seconds=2, fps=30, size="320x180", codec=None):
    """A real video file, made by the bundled ffmpeg."""
    binary = transcode.executable()
    args = [
        binary, "-hide_banner", "-loglevel", "error", "-y",
        "-f", "lavfi", "-i",
        "testsrc=size=%s:rate=%d:duration=%d" % (size, fps, seconds),
    ]
    if codec:
        args += ["-c:v", codec]
    if path.endswith(".mp4"):
        args += ["-pix_fmt", "yuv420p"]
    args.append(path)
    subprocess.check_call(args, stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT)
    return path


# --- finding it -------------------------------------------------------------


class TestLookup:
    def test_a_binary_ships_with_the_package(self):
        """The whole point of bundling: an animator installs a .mod file and a
        folder and video reference works, with nothing else to set up."""
        assert transcode.bundled_path() is not None
        assert os.path.isfile(transcode.bundled_path())

    def test_it_actually_runs(self):
        assert transcode.is_available()
        assert "ffmpeg version" in (transcode.version() or "")

    def test_an_explicit_override_wins(self, tmp_path):
        """A studio standardised on its own build gets to use it."""
        fake = os.path.join(str(tmp_path), "ffmpeg.exe")
        with open(fake, "w") as handle:
            handle.write("x")
        assert transcode.executable(fake) == fake

    def test_a_bad_override_falls_back_rather_than_failing(self):
        """A stale path in a settings file must not take video reference with
        it -- the bundled binary is right there."""
        found = transcode.executable("Z:/nope/ffmpeg.exe")
        assert found == transcode.bundled_path()


# --- reading a video --------------------------------------------------------


@requires_ffmpeg
class TestProbe:
    def test_reads_the_shape_of_a_video(self, tmp_path):
        path = make_video(os.path.join(str(tmp_path), "clip.mp4"),
                          seconds=2, fps=30, size="320x180")
        found = transcode.probe(path)
        assert found is not None
        assert (found["width"], found["height"]) == (320, 180)
        assert abs(found["duration"] - 2.0) < 0.3
        assert abs(found["fps"] - 30.0) < 0.5

    def test_a_file_that_is_not_a_video_reads_as_none(self, tmp_path):
        path = os.path.join(str(tmp_path), "notreally.mp4")
        with open(path, "w") as handle:
            handle.write("nope")
        assert transcode.probe(path) is None

    def test_a_missing_file_reads_as_none(self):
        assert transcode.probe("Z:/gone/clip.mp4") is None


# --- the arguments ----------------------------------------------------------


class TestArguments:
    def test_the_output_rate_is_the_one_asked_for(self, tmp_path):
        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, 720, "jpg")
        assert "-r" in args
        assert args[args.index("-r") + 1] == "24.0000"

    def test_the_scale_filter_never_upscales(self, tmp_path):
        """Blowing a 480p reference up to 720 spends disk to add nothing."""
        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, 720, "jpg")
        assert "min(720,ih)" in args[args.index("-vf") + 1]

    def test_jpeg_keeps_full_chroma(self, tmp_path):
        """4:2:0 stores colour at half resolution in both directions. Invisible
        on a photographed performance, and it is exactly what wrecks the case
        this tool keeps being pointed at: coloured text on a flat background
        comes back with fringed edges that more resolution cannot fix."""
        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, transcode.NATIVE, "jpg")
        assert args[args.index("-pix_fmt") + 1] == "yuvj444p"

    def test_png_is_left_alone(self, tmp_path):
        """png is already lossless RGB -- a jpeg pixel format on it would be
        meaningless at best."""
        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, transcode.NATIVE, "png")
        assert "-pix_fmt" not in args
        assert "-q:v" not in args

    def test_changing_the_encoder_re_converts(self, tmp_path):
        """The cache is keyed on everything that changes the pixels, and the
        encoder settings are part of that. Without the version in the key,
        every animator who already had a cache would keep being served frames
        made by the old settings -- silently, forever."""
        path = str(tmp_path / "clip.mp4")
        with open(path, "wb") as handle:
            handle.write(b"not really a movie")

        key = transcode.cache_key(path, 24.0, 720, "jpg")
        original = transcode.ENCODER_VERSION
        try:
            transcode.ENCODER_VERSION = original + 1
            assert transcode.cache_key(path, 24.0, 720, "jpg") != key
        finally:
            transcode.ENCODER_VERSION = original

    def test_native_height_scales_nothing_at_all(self, tmp_path):
        """The blur an animator actually reports.

        720 is a fine cap for a performance, and destroys a screen recording:
        1920x1080 of small type resampled to 1280x720 and JPEG'd at 4:2:0 is
        not soft, it is unreadable, and scaling the plane up in the viewport
        cannot bring back pixels that were never written. NATIVE is the way
        out, and it has to mean NO filter -- a scale filter that happens to be
        identity still costs a full resample of every frame.
        """
        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, transcode.NATIVE, "jpg")
        assert "-vf" not in args
        # Everything else about the conversion is unchanged.
        assert args[args.index("-r") + 1] == "24.0000"
        assert "-an" in args and "-sn" in args

    def test_a_nonsense_height_means_native_rather_than_a_broken_filter(
        self, tmp_path
    ):
        """`scale=-2:'min(0,ih)'` is a filter ffmpeg refuses, and a height can
        arrive as None or a negative from a hand-edited settings.json."""
        for bad in (None, 0, -1, "", "nonsense"):
            args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                        24.0, bad, "jpg")
            assert "-vf" not in args

    def test_native_and_720_are_different_cache_entries(self, tmp_path):
        """Changing the setting must re-convert, not serve the blurry copy."""
        path = str(tmp_path / "clip.mp4")
        with open(path, "wb") as handle:
            handle.write(b"not really a movie")
        assert (transcode.cache_key(path, 24.0, 720, "jpg")
                != transcode.cache_key(path, 24.0, transcode.NATIVE, "jpg"))

    def test_audio_and_subtitles_are_dropped(self, tmp_path):
        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, 720, "jpg")
        assert "-an" in args and "-sn" in args

    def test_the_pattern_is_padded_so_maya_reads_it_as_a_sequence(
        self, tmp_path
    ):
        from animkit.core import media

        args = transcode.build_args("ffmpeg", "in.mp4", str(tmp_path),
                                    24.0, 720, "jpg")
        pattern = args[-1]
        assert "%04d" % 1 == "0001"
        # The name ffmpeg will write must be one core.media reads as a
        # sequence frame -- these two agreeing is what makes the whole path
        # work, and nothing else checks it.
        written = pattern % 1
        assert media.split_frame(written) is not None


# --- the cache --------------------------------------------------------------


class TestCache:
    def test_the_key_changes_with_every_setting_that_changes_pixels(self,
                                                                    tmp_path):
        path = os.path.join(str(tmp_path), "clip.mp4")
        with open(path, "w") as handle:
            handle.write("x")

        base = transcode.cache_key(path, 24.0, 720, "jpg")
        assert transcode.cache_key(path, 30.0, 720, "jpg") != base
        assert transcode.cache_key(path, 24.0, 1080, "jpg") != base
        assert transcode.cache_key(path, 24.0, 720, "png") != base

    def test_the_key_changes_when_the_video_does(self, tmp_path):
        """Re-rendering the reference and dropping it again has to reconvert.
        A key on the path alone serves yesterday's video forever."""
        import time

        path = os.path.join(str(tmp_path), "clip.mp4")
        with open(path, "w") as handle:
            handle.write("first")
        before = transcode.cache_key(path, 24.0, 720, "jpg")

        time.sleep(1.1)
        with open(path, "w") as handle:
            handle.write("second, and longer")
        assert transcode.cache_key(path, 24.0, 720, "jpg") != before

    def test_the_key_is_a_usable_folder_name(self, tmp_path):
        path = os.path.join(str(tmp_path), "my ref (take 2)+final.mp4")
        with open(path, "w") as handle:
            handle.write("x")
        key = transcode.cache_key(path, 24.0, 720, "jpg")
        assert all(c.isalnum() or c in "_.-" for c in key), key

    def test_an_unfinished_conversion_is_not_a_cache_hit(self, tmp_path):
        """A cancelled convert leaves frames behind. Served as a hit, they
        would be a silently truncated reference."""
        folder = os.path.join(str(tmp_path), "half")
        os.makedirs(folder)
        with open(os.path.join(folder, "frame.0001.jpg"), "w") as handle:
            handle.write("x")
        assert transcode.cached_sequence(folder) is None

        with open(os.path.join(folder, "animkit.done"), "w") as handle:
            handle.write("1")
        assert transcode.cached_sequence(folder) is not None


# --- converting for real ----------------------------------------------------


@requires_ffmpeg
class TestConversion:
    def test_an_mp4_becomes_a_sequence_maya_can_read(self, tmp_path):
        """The case that does not work at all otherwise: Maya cannot decode
        .mp4 on an image plane, in either mode."""
        from animkit.core import media

        source = make_video(os.path.join(str(tmp_path), "take01.mp4"),
                            seconds=2, fps=30)
        out = os.path.join(str(tmp_path), "cache")
        result = transcode.convert(source, fps=24, height=360, root=out)

        assert result is not None
        assert os.path.isfile(result.first_frame)
        found = media.sequence_of(result.first_frame)
        assert found is not None
        assert found.first == 1

    @pytest.mark.parametrize("name,codec", [
        ("take.mp4", None),
        ("take.mov", None),
        ("take.avi", "mjpeg"),
    ])
    def test_every_container_an_animator_actually_has(self, tmp_path, name,
                                                      codec):
        source = make_video(os.path.join(str(tmp_path), name),
                            seconds=1, fps=24, codec=codec)
        out = os.path.join(str(tmp_path), "cache")
        result = transcode.convert(source, fps=24, height=180, root=out)
        assert result is not None, name
        assert result.frames >= 20, (name, result.frames)

    def test_the_sequence_is_at_the_SCENE_rate_not_the_video_rate(self,
                                                                  tmp_path):
        """The one that decides whether the reference is animatable.

        A 30fps source converted at 24 must yield 24 frames per second of
        footage, so frame N of the sequence is frame N of the timeline. Keeping
        the source rate leaves every timing 25% out -- consistently, and
        invisibly until somebody tries to match a contact.
        """
        source = make_video(os.path.join(str(tmp_path), "clip.mp4"),
                            seconds=2, fps=30)
        out = os.path.join(str(tmp_path), "cache")
        result = transcode.convert(source, fps=24, height=180, root=out)
        assert result is not None
        assert 46 <= result.frames <= 50, result.frames

    def test_the_frames_are_capped_in_height_but_never_upscaled(self,
                                                                tmp_path):
        big = make_video(os.path.join(str(tmp_path), "big.mp4"),
                         seconds=1, size="1280x720")
        small = make_video(os.path.join(str(tmp_path), "small.mp4"),
                           seconds=1, size="320x180")
        out = os.path.join(str(tmp_path), "cache")

        shrunk = transcode.convert(big, fps=12, height=360, root=out)
        kept = transcode.convert(small, fps=12, height=360, root=out)
        assert transcode.probe(shrunk.first_frame)["height"] == 360
        assert transcode.probe(kept.first_frame)["height"] == 180

    def test_the_second_drop_of_the_same_video_is_a_cache_hit(self, tmp_path):
        source = make_video(os.path.join(str(tmp_path), "clip.mp4"),
                            seconds=1, fps=24)
        out = os.path.join(str(tmp_path), "cache")

        first = transcode.convert(source, fps=24, height=180, root=out)
        second = transcode.convert(source, fps=24, height=180, root=out)
        assert first.cached is False
        assert second.cached is True
        assert second.first_frame == first.first_frame

    def test_progress_is_reported_and_can_cancel(self, tmp_path):
        """A long conversion has to be stoppable, and stopping it must not
        leave a folder that the next drop serves as a complete sequence."""
        source = make_video(os.path.join(str(tmp_path), "long.mp4"),
                            seconds=4, fps=30)
        out = os.path.join(str(tmp_path), "cache")
        seen = []

        def watch(done, total):
            seen.append(done)
            return False if done > 5 else True

        result = transcode.convert(source, fps=24, height=180, root=out,
                                   progress=watch)
        assert result is None
        assert seen, "progress was never reported"

        folder = os.path.join(out, transcode.cache_key(source, 24.0, 180,
                                                       "jpg"))
        assert transcode.cached_sequence(folder) is None

    def test_a_file_that_is_not_a_video_converts_to_nothing(self, tmp_path):
        source = os.path.join(str(tmp_path), "notreally.mov")
        with open(source, "w") as handle:
            handle.write("nope")
        out = os.path.join(str(tmp_path), "cache")
        assert transcode.convert(source, root=out) is None

    def test_a_missing_file_converts_to_nothing(self, tmp_path):
        assert transcode.convert("Z:/gone/clip.mp4",
                                 root=str(tmp_path)) is None

    def test_the_cache_can_be_measured_and_cleared(self, tmp_path):
        source = make_video(os.path.join(str(tmp_path), "clip.mp4"),
                            seconds=1, fps=24)
        out = os.path.join(str(tmp_path), "cache")
        transcode.convert(source, fps=24, height=180, root=out)

        folders, size = transcode.cache_size(root=out)
        assert folders == 1 and size > 0

        assert transcode.clear_cache(root=out) == 1
        assert transcode.cache_size(root=out) == (0, 0)
